### ISSUE TITLE
Confused about the update of x in FISTA algorithm of the image deblurring part

### ISSUE THREAD

**Issue by Niurouxing** [scaperex/My_Projects#18]
Hello.
The line 31 in fista.m says that  x = y-((1/L )*grad).
It seems that the shrinkage/soft-threshold step is not involved.
According to "A FAST ITERATIVE SHRINKAGE-THRESHOLDING ALGORITHM" , the result of " y-((1/L )*grad)" should pass through the  shrinkage operator .
I wish you could check if there is anything wrong in this step.

**Comment by scaperex** [comment]
Hi @Niurouxing, sorry for the late reply, 
Anyways, in our case we took g(x) from the article to be zero, so the argmin in the p_l function (the update rule from the article) is convex in x with a single minimizer, in a stationary point which is the update rule as you wrote. 
Therefore the step is identical, again assuming g(x) is zero, otherwise of course it should be considered.
